Colormap
CDAT/jupyter-vcdat pull request #135
Opened 2019-08-26 21:28 UTC by sterlingbaldwin

2019-08-26 21:28 UTC, sterlingbaldwin commented
Not quite ready yet.

2019-08-29 23:48 UTC, downiec commented
As part of your PR, could you include the Jupyter Lab extensions/packages that you mentioned would be good to install?

2019-08-30 15:59 UTC, sterlingbaldwin commented
The "favorites" extension seams useful, but I dont see any difference with the other one. Also apparently the "open-from-path" didnt mean what I thought it did. I'll add the favorites for the time being.

2019-09-06 22:48 UTC, downiec commented
Once your branch has the latest master merged in, it'll be easier for me to review the code. Is the code review the only thing left for this branch or is it still a draft?

2019-09-09 23:49 UTC, downiec requested changes

2019-09-09 23:49 UTC, downiec commented on src/components/ColormapEditor.tsx
> +const default_colormaps = ['AMIP',
This all looks good to me! But I think the default_colormaps const should be moved to the constants.ts file, no? That's where we have the default GM and other stuff.

2019-09-09 23:49 UTC, downiec commented on src/CodeInjector.ts
> +    let cmd = `${gm_name}_${gm_group}.colormap = '${cm_name}'`;
There is some kind of issue going on with the graphic method and colormap code injection. I tried selecting a colormap but it gives an error due to the graphic method not being initialized. I was trying to look where the issue is but it doesn't seem straight forward, so let me know if you'd like me to troubleshoot it?

2019-09-10 00:38 UTC, downiec commented on src/CodeInjector.ts
> +    let cmd = `${gm_name}_${gm_group}.colormap = '${cm_name}'`;
I think I found out the issue and will have a fix for it.

2019-09-10 00:40 UTC, downiec commented on src/CodeInjector.ts
> +    let cmd = `${gm_name}_${gm_group}.colormap = '${cm_name}'`;
Minor styling issue: The variable names should match the camel case used by other variables in the file, not sure why this passed the linter

2019-09-10 00:56 UTC, downiec commented on src/components/VCSMenu.tsx
> +        debugger;
Should probably remove this.

2019-09-10 01:25 UTC, downiec approved these changes

2019-09-10 23:31 UTC, merged