Sidecar update to functionality
CDAT/jupyter-vcdat pull request #136
Opened 2019-08-28 20:55 UTC by downiec

Sidecar can be toggled off and on. Sidecar will be removed automatically if corresponding notebook is closed. Sidecar code is injected in notebook for users to see. When switching between notebooks, the corresponding sidecar is activated. Sidecars can no longer be closed manually (to prevent them from disappearing). Each notebook will have only one sidecar and it will display the last plot made in the sidecar.

2019-08-28 20:58 UTC, downiec commented
This PR resolves issues #124 and #125.

2019-08-28 21:28 UTC, sterlingbaldwin submitted a review, later dismissed
Mostly fine, I think its better to either keep all the constants variable names as caps, or to switch them all to camelcase, but not have a mix of the two.

2019-08-28 21:28 UTC, sterlingbaldwin commented on src/CodeInjector.ts
> +  DisplayMode,
We should probably stick to only using ALL CAPS for constants variable names.

2019-08-28 21:28 UTC, sterlingbaldwin commented on src/CodeInjector.ts
> +  getSidecarDisplayCommand
Same here

2019-08-28 21:28 UTC, sterlingbaldwin commented on src/LeftSideBarWidget.tsx
> +    // EXPERIMENTAL
should probably remove the EXPERIMENTAL comments if you're trying to merge into master.

2019-08-28 21:28 UTC, sterlingbaldwin commented on src/LeftSideBarWidget.tsx
> +        w.title.closable = false;
This is a down and dirty hack, I like it ;)

2019-08-28 21:28 UTC, sterlingbaldwin commented on src/components/VCSMenu.tsx
> +      previousDisplayMode: "not_set",
For "magic strings" like this, its usually better to use an enum, or just set it to null/undefined on initialization.

2019-08-28 21:43 UTC, downiec commented on src/components/VCSMenu.tsx
> +      previousDisplayMode: "not_set",
I was using a custom type I made, 'DisplayMode' which is in the constants file. It prevents me from typing anything except one of the acceptable string values 'notebook', 'sidecar' or 'not_set'.

2019-08-28 22:06 UTC, downiec commented on src/CodeInjector.ts
> +  DisplayMode,
I was originally thinking it would help me differentiate between constants and custom 'types', but I'll leave them as all caps.

2019-08-28 22:08 UTC, downiec commented on src/CodeInjector.ts
> +  getSidecarDisplayCommand
getSidecarDisplay is a function that generates an appropriate command string based on the parameters you give it, you think I should name it as a constant?

2019-08-28 22:09 UTC, downiec commented on src/LeftSideBarWidget.tsx
> +    // EXPERIMENTAL
Yeah I forgot to remove those, thanks for catching that!

2019-08-28 22:10 UTC, downiec commented on src/LeftSideBarWidget.tsx
> +        w.title.closable = false;
Haha yeah I tried to do it a clean way, but this ended up being the quickest/simplest solution I could find since the sidecar extension didn't give me much to work with ;)

2019-08-28 22:28 UTC, downiec commented on src/CodeInjector.ts
> +  DisplayMode,
Actually, I decided I would remove the custom types from the constants file, so that the constants file contains only constants.

2019-08-29 00:14 UTC, sterlingbaldwin commented on src/CodeInjector.ts
> +  DisplayMode,
Yup, I think thats the better move.

2019-08-29 00:15 UTC, sterlingbaldwin commented on src/CodeInjector.ts
> +  getSidecarDisplayCommand
If its not a constant value, it shouldnt be in the constants file. I think just put it in its own module.

2019-08-29 00:17 UTC, sterlingbaldwin commented on src/components/VCSMenu.tsx
> +      previousDisplayMode: "not_set",
Thats what I thought, this is exactly what an enum is for. I guess it doesnt really matter, but an enum is better because a) its easy to add new things, b) its impossible to add a wrong thing, c) its only a single byte instead of an entire string.

2019-08-29 00:18 UTC, downiec commented on src/CodeInjector.ts
> +  getSidecarDisplayCommand
Those are coming from the PythonCommand file, which holds all the Python code and Python related functions, its not part of the constants file

2019-08-29 00:26 UTC, downiec commented on src/components/VCSMenu.tsx
> +      previousDisplayMode: "not_set",
Yeah I remember trying enums before using the types, but I ran into some complication (don't remember what) with the 'ImageUnits' and 'ExportPlot types'. Also the type checker will highlight a wrong entry as an error and won't compile so it won't let you add a wrong thing either. I'll revisit these later though because I agree enums are good

2019-08-29 00:40 UTC, downiec commented on src/components/VCSMenu.tsx
> +      previousDisplayMode: "not_set",
Oh yeah now I remember, I used the types because I could then use the strings to generate the button text in the export modal automatically. If we ever add or remove an image unit or plot type (easy enough, just update the custom types), the export plot modal will automatically render the new options correctly. This also ensures the value of the option selected will be a valid type that can be used in the python commands. Anyway I went ahead and changed the DisplayMode into an enum as you suggested.

2019-08-29 16:10 UTC, sterlingbaldwin commented
All looks good to me now, thanks for the changes.

2019-08-29 17:04 UTC, downiec commented
Great! Thanks for the suggestions!

2019-08-30 16:31 UTC, sterlingbaldwin commented
I just merged this branch into my colormap branch so I could see how it worked in the real world. My one note on usability is that when you disable the sidecar close button you should hide it as well. It could be a bit confusing to have the little 'x' there but not have it do anything when the user clicks it.

2019-08-30 16:36 UTC, sterlingbaldwin requested changes
See my comment on requested usability changes.

2019-09-03 17:14 UTC, downiec commented
> I just merged this branch into my colormap branch so I could see how it worked in the real world. My one note on usability is that when you disable the sidecar close button you should hide it as well. It could be a bit confusing to have the little 'x' there but not have it do anything when the user clicks it.
> 
> Also, when the sidecar tab is collapsed and a new graphics method is selected, it suddenly pops open. Before this gets merged I would suggest three changes (these may require some research and work):
> 
> a) Hide the sidecare x button.
> b) Make the "plot to sidecare" switch open and close the sidecar tab.
> c) Make sure that the sidecar tab doesnt open when the "plot to sidecare" option is turned off.

I just want to mention that because of the way the sidecar is, I have to use little hacks and things to get it to behave the way I want. It doesn't have the interface to control them beyond some very basic things (so I have to directly access the node and maybe manipulate the DOM, which is not ideal). For example, I was trying to get the 'x' to disappear even before I made this PR, but it seems to not let you remove it, so I chose to fix that later and focus on more important functionality. I agree with all your usability suggestions and will try my best to get them done in time for release but I can't promise anything. I may have to make another PR to address these issues, thanks for the suggestions!

2019-09-05 00:47 UTC, sterlingbaldwin commented
Ya they dont have the best API for interfacing with the widget, its pretty bare bones. It might be possible to call "hide" and "open" through the jupyter widget interface (not sure it is, just a thought).

2019-09-05 16:37 UTC, downiec commented
I tried using the show and hide methods a while ago and what they do is show/hide the plot, but the tab stays open. That's why I had to resort to the activateById method to switch between sidecars. However yesterday I tapped into the ILabShell interface which lets me show and hide the shell panels. So I think I can get that all working. I'm still having a problem figuring out how to get rid of the 'x's though, and I was going to try to do a quick and dirty hack to delete the div that contains them, but getting to the div isn't straight forward. I think I'll leave the 'x' removal for another PR (it's not straight forward at all).

2019-09-05 22:20 UTC, downiec commented
I will have to make another PR to handle the 'X' on the sidecar tabs, and I'm also planning on improving the logic so that notebooks can be renamed without causing them to 'disconnect' with their respective sidecar. Ccurrently I track which sidecar belongs to which notebook by matching their name, which will cause issues if a notebook is renamed.

2019-09-06 19:28 UTC, sterlingbaldwin commented
Very nice. Its opening and closing like it should, and when I switch between notebooks it switches to the correct sidecare tab. I think that once its building correctly in circleci that this gets merged.

2019-09-06 20:19 UTC, downiec commented
Great! Sounds good. I noticed that when JupyterLab updated to 1.1, they changed the name of some icons/html elements. So I spent this morning updating the locators in the selenium tests and running some manual tests on my local Mac. The tests all passed locally so hopefully they'll pass on circleci now.

2019-09-06 20:33 UTC, merged