Images from nightly
CDAT/jupyter-vcdat pull request #138
Opened 2019-09-12 18:22 UTC by doutriaux1

@downiec the PR for docker images

2019-09-12 18:22 UTC, doutriaux1 commented on .circleci/config.yml
> +      #- linux_jupyter_vcdat
don't forget to put back on when publishing works

2019-09-12 18:23 UTC, doutriaux1 commented on .circleci/config.yml
> +      - run: *npm_publish
@downiec we need to publish to npm first. Images not built from an npm repo will not work on shifter.

2019-09-17 20:44 UTC, downiec requested changes
I'm having trouble finding out why this PR doesn't pass the tests, but it seems the the npm_publish step causes issues because of missing node_modules.
'jupyter-vcdat@2.1.0 clean /home/jovyan/project
> rimraf lib

sh: 1: rimraf: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! jupyter-vcdat@2.1.0 clean: `rimraf lib`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jupyter-vcdat@2.1.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
'
IF this could be fixed, there's also minor updates needed to reference 'cdat' docker org, instead of personal account.

2019-09-17 20:44 UTC, downiec commented on kube/Dockerfile.extension
> +FROM cdoutrix/vcdat_labextensions:latest
This can be updated to cdat/vcdat_labextensions:latest

2019-09-17 20:44 UTC, downiec commented on kube/Dockerfile.labextensions
> +FROM cdoutrix/vcdat_core:latest
Should be: FROM cdat/vcdat_core:latest

2019-09-17 20:44 UTC, downiec commented on kube/Dockerfile.labextensions
>  RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager && jupyter labextension install @jupyter-widgets/jupyterlab-sidecar && jupyter labextension install @jupyterlab/github && pip inst
Need to add the tutorial manager extension I made: && jupyter labextension install tutorial-manager-extension

2019-09-17 20:44 UTC, downiec commented on .circleci/config.yml
> +      docker build -f kube/Dockerfile.extension --no-cache --tag=cdoutrix/vcdat:nightly .
--tag=cdat/vcdat:nightly .

2019-09-17 20:44 UTC, downiec commented on .circleci/config.yml
> +      docker push cdoutrix/vcdat:nightly
docker push cdat/vcdat:nightly

2019-10-01 19:02 UTC, downiec commented on .circleci/config.yml
> +      #- linux_jupyter_vcdat
Done

2019-10-01 19:02 UTC, downiec commented on .circleci/config.yml
> +      - run: *npm_publish
Done

2019-10-01 19:03 UTC, downiec commented on kube/Dockerfile.extension
> +FROM cdoutrix/vcdat_labextensions:latest
Merged into single docker file.

2019-10-01 19:03 UTC, downiec commented on kube/Dockerfile.labextensions
>  RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager && jupyter labextension install @jupyter-widgets/jupyterlab-sidecar && jupyter labextension install @jupyterlab/github && pip inst
Done and merged into single docker file.

2019-10-01 19:03 UTC, downiec commented on .circleci/config.yml
> +      docker build -f kube/Dockerfile.extension --no-cache --tag=cdoutrix/vcdat:nightly .
Done

2019-10-01 19:04 UTC, downiec commented on .circleci/config.yml
> +      docker push cdoutrix/vcdat:nightly
Updates to config.yml have been performed.

2019-10-04 00:39 UTC, downiec approved these changes
Made the changes that I requested. Circleci workflow should work now.

2019-10-04 17:44 UTC, muryanto1 approved these changes

2019-10-04 17:52 UTC, merged