Install refactor
CDAT/jupyter-vcdat pull request #158
Opened 2020-02-29 03:32 UTC by downiec

This is an update to the installation process which seeks to consolidate deployment into a single source. Adds a new script: scripts/deploy_update.py which when run, will automatically update/create a corresponding Dockerfile and install_script.sh which contain the appropriate updated dependencies. The Dockerfile and install script can be further updated by modifying their corresponding templates (all located in the deploy folder). This PR also includes updates to the circleci config made by Lina, which will make circleci use the latest docker image for chrome and firefox testing. It will then use the same base image needed for CDAT and will run the install script to install vcdat to match what is installed locally. JupyterLab is pinned to version 1.2.1 for compatibility reasons. Migrating to JupyterLab 2.0 will be done in a later update.

2020-04-02 20:43 UTC, sterlingbaldwin approved these changes

2020-04-07 21:33 UTC, sterlingbaldwin approved these changes

2020-04-07 21:33 UTC, sterlingbaldwin commented
Go ahead and merge this once the tests are passing.

2020-04-10 19:10 UTC, muryanto1 requested changes

2020-04-10 19:10 UTC, muryanto1 commented on .circleci/OLDconfig.yml
> +      ./install_script.sh -v -d
I think we need to add "conda activate base" before running install_script.sh.

2020-04-10 19:10 UTC, muryanto1 commented on tests/PageObjects/Locator.py
> +                i += 1
i is not defined in this scope.

2020-04-10 19:10 UTC, muryanto1 commented on tests/PageObjects/Locator.py
> +                name = "[{}]_not_found{}.png".format(self.description, i)
line 33 and 34: should we increment i first?

2020-04-10 19:10 UTC, muryanto1 commented on tests/PageObjects/Locator.py
> +            name = "element_not_found.png"
if the argument "name" is not empty, then we get to this else case, and you are setting 'name' to "element_not_found.png", i.e. overwriting the passed in argument. is that the intention?

2020-04-10 19:22 UTC, downiec commented on tests/PageObjects/Locator.py
> +                name = "[{}]_not_found{}.png".format(self.description, i)
I guess we can start at 1 instead of 0.

2020-04-10 19:25 UTC, downiec commented on tests/PageObjects/Locator.py
> +            name = "element_not_found.png"
Good catch, I will fix!

2020-04-14 16:49 UTC, downiec commented
@muryanto1 Tests are passing after I implemented your suggestions. Can you re-review and then I'll merge?

2020-04-14 17:49 UTC, muryanto1 commented on tests/PageObjects/Locator.py
> +            name = "element_not_found.png"
The fix looks good. I think you can move line 31 to be at the beginning of the __save_screenshot__(),
and you can remove i = 0 from line 37 and 42.
No big deal. I can see the code should work as is. Thanks.

2020-04-14 17:50 UTC, muryanto1 reviewed
approved

2020-04-14 17:57 UTC, muryanto1 approved these changes

2020-04-14 19:59 UTC, merged