trying from a new branch somehow the 'kube' branch seems to always pu…
CDAT/jupyter-vcdat pull request #94
Opened 2019-04-12 14:35 UTC by doutriaux1

…ll from master when uploading

2019-04-30 16:51 UTC, doutriaux1 commented
@downiec I think this is ready.

2019-05-01 22:24 UTC, downiec requested changes
Not sure why the linux test is failing?

2019-05-01 22:25 UTC, doutriaux1 commented
@downiec I merged master in we will see if it helps.

2019-05-07 16:19 UTC, downiec approved these changes

2019-05-08 04:26 UTC, merged